[package]
name = "libfrad"
version = "0.0.0"
authors = ["Ha∆ûuL"]
license = "Archivist Licence"
edition = "2024"

[lib]
name = "libfrad"
path = "lib.rs"
crate-type = ["rlib"]

[dependencies]
half = "2.7.1"
miniz_oxide = "0.8.9"
palmfft = "1.3.1"
